production test

diff --git a/src/wombat_docker/Dockerfile b/src/wombat_docker/Dockerfile
--- a/src/wombat_docker/Dockerfile
+++ b/src/wombat_docker/Dockerfile
@@ -11,24 +11,14 @@ FROM python:3.11-slim
 WORKDIR /app
 
 # Require wombat UID/GID to be provided by the Linux build host.
-ARG WOMBAT_UID
-ARG WOMBAT_GID
+ARG WOMBAT_UID=1000
+ARG WOMBAT_GID=1000
+ENV WOMBAT_UID=${WOMBAT_UID}
+ENV WOMBAT_GID=${WOMBAT_GID}
 
 RUN set -eux; \
 	test -n "${WOMBAT_UID}"; \
 	test -n "${WOMBAT_GID}"
-
-RUN printf '%s\n' '#!/bin/sh' 'set -eu' \
-	'uid="${WOMBAT_UID:?WOMBAT_UID is required}"' \
-	'gid="${WOMBAT_GID:?WOMBAT_GID is required}"' \
-	'printf "WOMBAT_UID=%s\nWOMBAT_GID=%s\n" "$uid" "$gid" > /app/wombat_env.env' \
-	> /usr/local/bin/collect-wombat-ids.sh \
-	&& chmod +x /usr/local/bin/collect-wombat-ids.sh
-
-ENV WOMBAT_UID=${WOMBAT_UID}
-ENV WOMBAT_GID=${WOMBAT_GID}
-
-RUN /usr/local/bin/collect-wombat-ids.sh
 
 # Create and activate virtualenv first
 RUN python -m venv /app/venv
@@ -43,7 +33,7 @@ COPY helper/ ./helper/
 COPY wombat_docker/capybara_app.py ./
 COPY wombat_docker/validator.py ./
 
-RUN printf '%s\n' '#!/bin/sh' 'set -e' '/usr/local/bin/collect-wombat-ids.sh' 'set -a' '[ -f /app/wombat_env.env ] && . /app/wombat_env.env' 'set +a' 'exec "$@"' > /usr/local/bin/docker-entrypoint.sh \
+RUN printf '%s\n' '#!/bin/sh' 'set -eu' 'uid="${WOMBAT_UID:?WOMBAT_UID is required}"' 'gid="${WOMBAT_GID:?WOMBAT_GID is required}"' 'printf "WOMBAT_UID=%s\nWOMBAT_GID=%s\n" "$uid" "$gid" > /app/wombat_env.env' 'set -a' '[ -f /app/wombat_env.env ] && . /app/wombat_env.env' 'set +a' 'exec "$@"' > /usr/local/bin/docker-entrypoint.sh \
 	&& chmod +x /usr/local/bin/docker-entrypoint.sh
 
 ENV FAILURE_DIR=/mnt/wombat/failure
